### PR TITLE
Make `Name (Full)` field mapping work

### LINKED ISSUE #21: Field mappings fail if full name is selected
If a form's `Name (Full)` field is used in feed settings, it will not be sent to ConvertKit and will generate a PHP notice.

This is because the value of the `Name (Full)` field is determined after form submission; it's not an actual `<input>` in the form, but we're currently trying to access it directly [here](https://github.com/ConvertKit/convertkit-gravity-forms/blob/0f2ef8f03b4238e793c9fab6f06523709cc9e6bd/components/gravityforms/class-gf-convertkit.php#L291).

image

### PR DESCRIPTION
**Pull request by tnorthcutt**
Closes #21

Uses Gravity Forms' built in GFAddOn::get_field_value() to get a calculated
value of the `Name (Full)` field rather than trying (and failing) to access
it directly from a form entry.

### CODE REVIEW

File: components/gravityforms/class-gf-convertkit.php [hunk 1]
```diff
@@ -288,7 +294,7 @@ public function process_feed( $feed, $entry, $form ) {
 			}
 		}
 
-		ckgf_convertkit_api_add_email( $form_id, $entry[ $field_map_e ], $entry[ $field_map_n ], null, $fields );
+		ckgf_convertkit_api_add_email( $form_id, $email, $name, null, $fields );
```
Comment (pothibo) [inline components/gravityforms/class-gf-convertkit.php]: Are these safe to be null?

Comment (tnorthcutt) [reply components/gravityforms/class-gf-convertkit.php]: Yep, there's a [check here](https://github.com/ConvertKit/convertkit-gravity-forms/blob/0f2ef8f03b4238e793c9fab6f06523709cc9e6bd/functions/convertkit.php#L30) in `ckgf_convertkit_api_request()` to fetch the API key if it's not set. I don't love how that's all done and will probably refactor at some point, but it's safe.
